micronaut:
  metrics:
    enabled: false
    export:
      statsd:
        enabled: false
  server:
    port: 8087
    max-request-size: '5000GB'
    multipart:
      enabled: true
      max-file-size: '5000GB'
      mixed: true
  application:
    name: archive
  router:
    versioning:
      enabled: true
      default-version: 1

jackson:
  bean-introspection-module: true
  serialization:
    writeDatesAsTimestamps: true
    writeDateTimestampsAsNanoseconds: false
  deserialization:
    readDateTimestampsAsNanoseconds: false
